typedef enum {
  NODE_HEADER,
  NODE_EMPH,
  NODE_LINEBREAK,
  NODE_ITALICS,
  NODE_EMPH_ITALICS,
  NODE_BLOCKQUOTES,
  NODE_LIST_ORDERED,
  NODE_LIST_UNORDERED,
  NODE_LIST_INDENT,
  NODE_CODE_BACKTICK,
  NODE_HRULE,
  NODE_LINK,
  NODE_IMAGE,
  NODE_MATH,
  NODE_UNKNOWN
} NodeType;
